name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        file:
          - Dockerfile
          - Dockerfile.slim
          - Dockerfile.alpine
          - Dockerfile.15-buster-slim
          - Dockerfile.15-slim
          - Dockerfile.14-buster-slim
          - Dockerfile.14-slim

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file ${{ matrix.file }}
